lower(http.user_agent) contains "ahrefsbot" or 
lower(http.user_agent) contains "alittle" or 
lower(http.user_agent) contains "aliyunsecbot" or 
lower(http.user_agent) contains "aiohttp" or 
lower(http.user_agent) contains "amazonbot" or 
lower(http.user_agent) contains "apache-httpclient" or 
lower(http.user_agent) contains "assetnote" or 
lower(http.user_agent) contains "backlinksextendedbot" or 
lower(http.user_agent) contains "baiduspider" or 
lower(http.user_agent) contains "barkrowler" or 
lower(http.user_agent) contains "bdvbot" or 
lower(http.user_agent) contains "beanserver" or 
lower(http.user_agent) contains "binance" or 
lower(http.user_agent) contains "bitdiscovery" or 
lower(http.user_agent) contains "bubing" or 
lower(http.user_agent) contains "bytespider" or 
lower(http.user_agent) contains "cc_bot" or 
lower(http.user_agent) contains "ccbot" or 
lower(http.user_agent) contains "censys" or 
lower(http.user_agent) contains "claudebot" or 
lower(http.user_agent) contains "cms detector" or 
lower(http.user_agent) contains "cms-checker" or 
lower(http.user_agent) contains "curl" or
lower(http.user_agent) contains "dataforseobot" or 
lower(http.user_agent) contains "dotbot" or 
lower(http.user_agent) contains "env-checker" or 
lower(http.user_agent) contains "ev-crawler" or 
lower(http.user_agent) contains "expo-research-bot" or 
lower(http.user_agent) contains "fasthttp" or 
lower(http.user_agent) contains "fastscan" or 
lower(http.user_agent) contains "firefoxversion" or 
lower(http.user_agent) contains "flyriverbot" or 
lower(http.user_agent) contains "freepbx-scanner" or 
lower(http.user_agent) contains "genomecrawlerd" or 
lower(http.user_agent) contains "go-http" or 
lower(http.user_agent) contains "grammarly" or 
lower(http.user_agent) contains "gptbot" or 
lower(http.user_agent) contains "grequests" or 
lower(http.user_agent) contains "ivre-masscan" or 
lower(http.user_agent) contains "jugendschutzprogramm" or 
lower(http.user_agent) contains "keydrop" or 
lower(http.user_agent) contains "l9explore" or 
lower(http.user_agent) contains "l9scan" or 
lower(http.user_agent) contains "l9tcpid" or 
lower(http.user_agent) contains "libredtail" or 
lower(http.user_agent) contains "lynx" or 
lower(http.user_agent) contains "masscan" or 
lower(http.user_agent) contains "mediatoolkitbot" or 
lower(http.user_agent) contains "meta-externalagent" or 
lower(http.user_agent) contains "mj12bot" or 
lower(http.user_agent) contains "netcraftsurveyagent" or 
lower(http.user_agent) contains "okhttp" or 
lower(http.user_agent) contains "opensiteexplorer" or
lower(http.user_agent) contains "palo alto" or
lower(http.user_agent) contains "pandalytics" or 
lower(http.user_agent) contains "python-httpx" or 
lower(http.user_agent) contains "python-requests" or 
lower(http.user_agent) contains "python-urllib" or 
lower(http.user_agent) contains "recordedfuture" or 
lower(http.user_agent) contains "scrapy" or 
lower(http.user_agent) contains "securityheaders" or 
lower(http.user_agent) contains "seekportbot" or 
lower(http.user_agent) contains "semrush" or 
lower(http.user_agent) contains "serankingbacklinksbot" or 
lower(http.user_agent) contains "serpstatbot" or 
lower(http.user_agent) contains "shapbot" or 
lower(http.user_agent) contains "smtbot" or 
lower(http.user_agent) contains "sogou" or 
lower(http.user_agent) contains "sqalix-multi-worker" or 
lower(http.user_agent) contains "terracotta" or 
lower(http.user_agent) contains "testuseragent" or 
lower(http.user_agent) contains "threatview" or 
lower(http.user_agent) contains "tineye-bot-live" or 
lower(http.user_agent) contains "tutanota" or 
lower(http.user_agent) contains "ugaresearchagent" or 
lower(http.user_agent) contains "valimail" or 
lower(http.user_agent) contains "xfa1" or 
lower(http.user_agent) contains "zend" or 
lower(http.user_agent) contains "zgrab" or 
lower(http.user_agent) contains "zoominfobot"

